//
//  DmEnumDef.h
//  GyeongbukUni
//
//  Created by kdsooi on 13. 7. 23..
//  Copyright (c) 2013년 kdsooi. All rights reserved.
//

#ifndef emdm_DmEnumDef_h
#define emdm_DmEnumDef_h

typedef enum
{
    OK = 200,
    NO_CONTENT = 204,
    
    BAD_REQUEST = 400,
    INVALID_CREDENTIALS = 401,
    INVALID_CREDENTIALS_TYPE = 402,
    NOT_FOUND = 404,
    MISSING_CREDENTIALS = 407,
    
    MISSING_DEVICE_TYPE = 430,
    INVALID_DEVICE_TYPE = 431,
    MISSING_DEVICE_NUMBER = 432,
    MISSING_DEVICE_ID = 433,
    DEVICE_NOT_FOUND = 434,
    DEVICE_ATTENDANCE_ALREADY_EXISTS = 435,
    DEVICE_PHONENUMBER_NOT_FOUND = 436,
    INVALID_STUDENT_IN_CLASS = 437,
    
    
    DATASTORE_FAILURE = 510,
    
    CLIENT_NEXT = 1000,
    CLIENT_END = 1001,
    
    CLIENT_ERROR_ENCODE = 1200,
    CLIENT_ERROR_DECODE = 1201,
    
    CLIENT_ERROR_HTTP = 1300,
    CLIENT_ERROR_HTTP_POST = 1301,
    CLIENT_ERROR_HTTP_GET = 1302,
    
    CLIENT_ERROR_CRED = 1350,
    CLIENT_ERROR_NULL_MOD = 1351,
    CLIENT_ERROR_MODATA = 1352,
    CLIENT_ERROR_NULL_MODATA = 1353,
    CLIENT_ERROR_CMD = 1354,
    CLIENT_ERROR_NULL_CMD = 1355,
    CLIENT_ERROR_NULL_END = 1356,
    CLIENT_ERROR_STATUS = 1357,
    CLIENT_ERROR_NULL_STATUS = 1358,
    CLIENT_ERROR_ALERT = 1359,
    
    
    CLIENT_ERROR_NULL_LESSON = 1360,
    
    CLIENT_ERROR_NULL_SERVER_ID = 1400,
    CLIENT_ERROR_NULL_HTTP_RESPONSE = 1401,
    CLIENT_ERROR_NULL_INPUT = 1402,
} AgentStatus;

typedef enum
{
    PROCESS_INIT = 0,
    PROCESS_PKG1,
    PROCESS_PKG2,
    PROCESS_PKG3,
    PROCESS_PKG4,
    PROCESS_END,
    PROCESS_ERROR,
    PROCESS_FINISH,
} AgentMessage;

#endif
